- name: Auth to the cluster 
  uri:
    url: "{{ api_url_v3 }}/clusters/list"
    body:
      kind: cluster
      sort_order: ASCENDING
      offset: 0
      length: 10
      sort_attribute: ''
    method: POST
    validate_certs: false
    force_basic_auth: true
    body_format: json
    user: "{{ prism_user }}"
    password: "{{ prism_password }}"
    status_code: 200
    return_content: true
  register: login
  delegate_to: localhost

- name: Set fact for session cookie
  set_fact:
    session_cookie: "{{ login.set_cookie }}"
