- name: Gets subnets list
  uri:
    url: "{{ api_url_v3 }}/subnets/list"
    body:
      length: 1000
      offset: 0
      filter: ""
    method: POST
    validate_certs: false
    body_format: json
    status_code: 200
    headers: 
      Cookie: "{{ session_cookie }}"
  delegate_to: localhost
  register: subnets_list

- name: Gets subnet UUID from its name
  set_fact:
    subnet_uuid: '{{ subnets_list.json.entities | json_query(my_query)|first }}'
  vars:
    my_query: "[? status.name=='{{ vm_subnet_name }}' && spec.cluster_reference.name=='{{ cluster_name }}'].metadata.uuid"

- name: Gets subnet details
  uri:
    url: "{{ api_url_v3 }}/subnets/{{ subnet_uuid }}"
    body:
      length: 100
      offset: 0
      filter: ""
    method: GET
    validate_certs: false
    body_format: json
    status_code: 200
    headers:
      Cookie: "{{ session_cookie }}"
  delegate_to: localhost
  register: subnet_details
