---

- name: Get a list of all VMs
  uri:
    url: "{{ api_url_v2 }}/vms/"
    method: GET
    validate_certs: false
    #    body_format: json
    status_code: 200
    force_basic_auth: true
    url_username: "{{ prism_user }}"
    url_password: "{{ prism_password }}"
  register: vms_list
  delegate_to: localhost

- name: Get VM UUID from its name
  set_fact:
    vm_uuid: '{{ vms_list.json.entities | json_query(my_query)|first }}'
  vars:
    my_query: "[? name=='{{ inventory_hostname }}'].uuid"

- name: Get a list of VM snapshots
  uri:
    url: '{{ api_url_v2 }}/snapshots/?vm_uuid={{ vm_uuid }}'
    method: GET
    validate_certs: false
    force_basic_auth: true
    url_username: "{{ prism_user }}"
    url_password: "{{ prism_password }}"
    return_content: true
    status_code: 200
  register: existing_snapshots
  delegate_to: localhost

- name: Delete VM snapshots
  uri:
    url: '{{ api_url_v2 }}/snapshots/{{ item.uuid }}'
    method: DELETE
    validate_certs: false
    force_basic_auth: true
    url_username: "{{ prism_user }}"
    url_password: "{{ prism_password }}"
    status_code: 201
  with_items: '{{ existing_snapshots.json.entities }}'
  delegate_to: localhost
